# Generated by Django 3.0.4 on 2020-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_published',
            field=models.BooleanField(),
        ),
    ]
