# Generated by Django 3.0.4 on 2020-04-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200402_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_published',
        ),
    ]
