# Generated by Django 3.0.4 on 2020-04-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_activity_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='link',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.Activity'),
        ),
    ]
